name: Docker Image CI

on:
  push:
     branches:
      - main

jobs:
   flask-image-to-docker-hub:
     runs-on: ubuntu-latest
     steps:
       - name: docker login
         uses: actions/checkout@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

       - name: Build and push Docker image
         run: |
           docker build -t pythonflask-app .
           docker tag pythonflask-app ${{ secrets.DOCKERHUB_USERNAME }}/pythonflask-app:latest0
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/pythonflask-app:latest0
