name: PythonFlask Docker Build and Push

#on: [push] # When pushing to any branch then run this action
#on:
##  workflow_dispatch:  # Manually triggered event
on:
  push:
    branches:
      - main

jobs:
  flask-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: actions/checkout@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}/flask:1.0
          tags: manasabalagoni1@gmail.com/abcdef/flask:1.0
