name: PythonFlask Docker Build and Push

#on: [push] # When pushing to any branch then run this action
#on:
##  workflow_dispatch:  # Manually triggered event
on:
  push:
    branches:
      - main

jobs:
  flask-image-to-docker-hub:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitpythonflaskapp:latest09
