name: PythonFlask Docker Build and Push

####on: [push] # When pushing to any branch then run this action

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push_value:
        description: 'whether to Push Docker image to Docker Hub'
        type: boolean
        required: true
        default: false

jobs:
  flask-image-to-docker-hub:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
           
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Tag Number
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then

            if [[ "${{ github.event.inputs.push_value }}" == 'true' ]]; then
              echo "::set-output name=TAG_NUMBER::${{ github.run_number }}-dev";
              push_needed ='true' 
            else
              echo "::set-output name=TAG_NUMBER::${{ github.run_number }}-dev";
              push_needed = 'false' 
            fi
          elif [[ "${{ github.event_name }}" == 'push' ]]; then
            push_needed ='true'  # For non-workflow dispatch events, always push
            echo "::set-output name=TAG_NUMBER::${{ github.run_number }}"; 
            echo "::set-output name=PUSH_NEEDED::${push_needed}}"
          else 
            echo "::set-output name=TAG_NUMBER:: image is cannot be pushed to docker Hub";
          fi
      - name: Build and push Docker image
        if: steps.set-tag.outputs.PUSH_NEEDED == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          #push: ${{ github.event.inputs.push_value == 'true' }} 
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:${{ steps.set-tag.outputs.TAG_NUMBER }}
          #${{ github.run_number }}