name: PythonFlask Docker Build and Push

#on: [push] # When pushing to any branch then run this action
#on:
##  workflow_dispatch:  # Manually triggered event
on:
  push:
    branches:
      - main

jobs:
  flask-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: actions/checkout@v1
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 9959574446/python-flask-app:latest
